fx_version 'cerulean'
game 'gta5'
lua54 'yes'

author 'Azure(TheStoicBear)'
description 'Azure Framework'
version '1.5.5-death-v4b'

shared_scripts {
    '@ox_lib/init.lua',
    'config/config.lua',
    'config/character_defaults.lua',
    'config/admin_defaults.lua',
    'modules/immersion/config.lua',
    'modules/immersion/shared.lua',
    'modules/dmv/config.lua',
    'modules/fuel/config.lua',
    'modules/id/config.lua',
    'modules/banking/config.lua',
    'modules/chat/config.lua',
    'modules/insurance/config.lua',
    'modules/morsdelivery/config.lua',
    'modules/dailyrewards/config.lua',
    'modules/death/config.lua',
    'modules/housing/config.lua',
    'modules/housing/shared/init.lua',
    'modules/housing/shared/utils.lua',
    'modules/housing/shared/money.lua',
}

server_scripts {
    '@oxmysql/lib/MySQL.lua',
    'init.lua',
    'schema.lua',
    'core/server.lua',
    'bridge/server.lua',
    'exports/server.lua',
    'parking/server.lua',
    'departments/server.lua',
    'characterui/server.lua',
    'characterui/cutscene_server.lua',
    'admin/server.lua',
    'modules/immersion/server.lua',
    'modules/dmv/server.lua',
    'modules/fuel/server.lua',
    'modules/id/server.lua',
    'modules/banking/server.lua',
    'modules/chat/server/main.lua',
    'modules/insurance/server.lua',
    'modules/insurance/wreck_server.lua',
    'modules/plates/server.lua',
    'modules/morsdelivery/server.lua',
    'modules/dailyrewards/server.lua',
    'modules/death/server.lua',
    'modules/death/source/serv/server.lua',
    'modules/housing/shared/framework.lua',
    'modules/housing/server/storage.lua',
    'modules/housing/server/main.lua',
    'modules/housing/server/garage.lua',
    'modules/housing/server/portal.lua',
    'modules/housing/server/upgrades.lua',
    'modules/housing/server/mailbox.lua',
    'modules/housing/server/furniture.lua',

}

client_scripts {
    'core/client.lua',
    'bridge/client.lua',
    'exports/client.lua',
    'parking/client.lua',
    'departments/client.lua',
    'discord/presence.lua',
    'characterui/client.lua',
    'characterui/cutscene_client.lua',
    'characterui/shops.lua',
    'admin/client.lua',
    'modules/immersion/client.lua',
    'modules/dmv/client.lua',
    'modules/fuel/client.lua',
    'modules/id/client.lua',
    'modules/banking/client.lua',
    'modules/chat/client/main.lua',
    'modules/insurance/client.lua',
    'modules/insurance/wreck_client.lua',
    'modules/plates/client.lua',
    'modules/morsdelivery/client.lua',
    'modules/dailyrewards/client.lua',
    'modules/death/debug_probe.lua',
    'modules/death/source/clie/client.lua',
    'modules/death/source/veh/client.lua',
    'modules/death/aiems.lua',
    'modules/housing/client/state.lua',
    'modules/housing/client/ui.lua',
    'modules/housing/client/target.lua',
    'modules/housing/client/garage.lua',
    'modules/housing/client/furniture.lua',
    'modules/housing/client/placement.lua',
    'modules/housing/client/main.lua',
}

files {
    'html/config.js',
    'html/index.html',
    'html/logo.png',
    'html/Stoic-2025-11-27_20-20-42-6928b29a61ed6.png',
    'html/character/index.html',
    'html/character/config.js',
    'html/character/map.png',
    'html/admin/index.html',
    'html/mors/index.html',
    'characterui/spawns.json',
    'characterui/cutscene_seen.json',
    'admin/reports.json',
    'config/departments_runtime.json',
    'modules/immersion/data/props_state.json',
    'modules/immersion/data/relationships.json',
    'modules/immersion/data/complaints.json',
    'admin/sql/schema.sql',
    'modules/fuel/html/index.html',
    'modules/id/html/index.html',
    'modules/banking/ui/index.html',
    'modules/chat/html/index.html',
    'modules/chat/html/app.js',
    'modules/chat/html/style.css',
    'modules/chat/html/assets/**/*',
    'modules/insurance/html/**/*',
    'modules/insurance/sql/**/*',
    'modules/morsdelivery/html/**/*',
    'modules/dailyrewards/html/**/*',
    'modules/dailyrewards/sql/**/*',
    'modules/death/html/**/*',
    'modules/housing/html/**/*',
    'modules/housing/data/**/*',
    'modules/housing/sql/**/*',
    'init.lua',

}

ui_page 'html/index.html'

client_exports {
    "refreshHUD",
    "updateHUD",
    "RefreshDiscordPresence",
    "SetDiscordPresenceOverride",
    "SetDiscordJob",
    "GetBridgeClientSnapshot",
    "GetBridgeClientMetadata",
    "SetBridgeClientMetadata"
}

server_exports {
    "addMoney",
    "deductMoney",
    "depositMoney",
    "withdrawMoney",
    "transferMoney",
    "GetMoney",
    "UpdateMoney",
    "sendMoneyToClient",
    "claimDailyReward",
    "getDiscordID",
    "GetDiscordID",
    "isAdmin",
    "GetPlayerCharacter",
    "getActiveCharacter",
    "GetActiveCharacter",
    "GetCharacter",
    "getCharacter",
    "SetActiveCharacter",
    "setActiveCharacter",
    "ClearActiveCharacter",
    "clearActiveCharacter",
    "GetPlayerCharacterName",
    "GetPlayerCharacterNameSync",
    "GetPlayerMoney",
    "logAdminCommand",
    "getPlayerJob",
    "setPlayerJob",
    "hasHuntingLicense",
    "setHuntingLicense",
    "isHuntingLicenseEnabled",
    "getConfiguredDepartments",
    "saveConfiguredDepartments",
    "upsertConfiguredDepartment",
    "removeConfiguredDepartment",
    "createReport",

    "AddMoney",
    "DeductMoney",
    "DepositMoney",
    "WithdrawMoney",
    "TransferMoney",
    "ClaimDailyReward",
    "HasHuntingLicense",
    "SetHuntingLicense",
    "IsHuntingLicenseEnabled",
    "SetPlayerJob",
    "GetBridgePlayerSnapshot",
    "GetBridgePlayers",
    "GetBridgeMoney",
    "AddBridgeMoney",
    "RemoveBridgeMoney",
    "SetBridgeMoney",
    "GetBridgeMetadata",
    "SetBridgeMetadata",
    "BridgeNotify",
    "GetBridgeItemCount",
    "HasBridgeItem",
    "GetBridgeItem",
    "AddBridgeItem",
    "RemoveBridgeItem"
}
